---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: ../../data_bags
  data_path: test/shared

busser:
  sudo: true

platforms:
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[test-helper]
      - recipe[eulipion-cleanspeak::default]
    attributes:
